# Generated by Django 3.0.7 on 2020-06-05 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('num', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive', models.DateField()),
                ('contract', models.DateField()),
                ('delivery', models.DateField()),
                ('idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.Project_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Project_cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real', models.DecimalField(decimal_places=3, max_digits=6)),
                ('total', models.DecimalField(decimal_places=3, max_digits=6)),
                ('real_expect', models.BooleanField()),
                ('total_expect', models.BooleanField()),
                ('idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.Project_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Project_construct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_width', models.IntegerField()),
                ('scale_length', models.IntegerField()),
                ('scale_depth', models.IntegerField()),
                ('tm', models.IntegerField()),
                ('steel', models.IntegerField()),
                ('earth', models.IntegerField()),
                ('scale_expect', models.BooleanField()),
                ('tm_expect', models.BooleanField()),
                ('steel_expect', models.BooleanField()),
                ('earth_expect', models.BooleanField()),
                ('idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.Project_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Project_company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execute', models.CharField(max_length=30)),
                ('construct', models.CharField(max_length=30)),
                ('subcontract', models.CharField(max_length=30)),
                ('plan', models.CharField(max_length=30)),
                ('execute_expect', models.BooleanField()),
                ('construct_expect', models.BooleanField()),
                ('subcontract_expect', models.BooleanField()),
                ('plan_expect', models.BooleanField()),
                ('idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.Project_Info')),
            ],
        ),
    ]
