# Generated by Django 3.0.7 on 2020-06-05 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_project_company_project_construct_project_cost_project_info_project_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.BinaryField()),
                ('place', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('cf_start', models.TimeField()),
                ('cf_end', models.TimeField()),
                ('pjt_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.Project_Info')),
            ],
        ),
        migrations.RenameField(
            model_name='project_company',
            old_name='idx',
            new_name='pjt_idx',
        ),
        migrations.RenameField(
            model_name='project_construct',
            old_name='idx',
            new_name='pjt_idx',
        ),
        migrations.RenameField(
            model_name='project_cost',
            old_name='idx',
            new_name='pjt_idx',
        ),
        migrations.RenameField(
            model_name='project_schedule',
            old_name='idx',
            new_name='pjt_idx',
        ),
        migrations.AddField(
            model_name='project_construct',
            name='shape',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Conference_visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('cfr_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.Conference_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Conference_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=30)),
                ('summary', models.CharField(max_length=200)),
                ('cfr_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.Conference_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Conference_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=30)),
                ('summary', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('cfr_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.Conference_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Conference_attender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility', models.CharField(max_length=20)),
                ('agency', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('cfr_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.Conference_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Conference_approve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('cfr_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.Conference_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Conference_action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=30)),
                ('summary', models.CharField(max_length=200)),
                ('cfr_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.Conference_Info')),
            ],
        ),
    ]
