# Generated by Django 3.0.7 on 2020-06-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_auto_20200611_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_schedule',
            name='contract',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project_schedule',
            name='delivery',
            field=models.DateField(null=True),
        ),
    ]
