# Generated by Django 3.0.7 on 2020-06-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_auto_20200611_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference_content',
            name='stage',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='conference_info',
            name='department',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
