# Generated by Django 3.0.7 on 2020-06-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_auto_20200605_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_info',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project_info',
            name='num',
            field=models.IntegerField(),
        ),
    ]
