# Generated by Django 3.0.7 on 2020-06-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_auto_20200605_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference_content',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
